variable "subscription_id" {}
variable "client_id" {}
variable "client_secret" {}
variable "tenant_id" {}
variable "localadmin" {}
variable "localadminpw" {}
variable "resource_group_name" {}
variable "virtual_network_name" {}
variable "subnet_dmz_name" {}
variable "address_prefix" {}
variable "web01_ip_address" {}
variable "web02_ip_address" {}
variable "oracle01_ip_address" {}
variable "WebTierLB_ip_address" {}
variable "puppet_ip_address" {}
variable "subnet_inside_name" {}
variable "address_prefix_inside" {}
